from typing import Literal

from ...consts import ObjectPositionType

from ...modifiable_values import DamageMultiplyValue
from .base import UsageTeamStatus


class IllusoryBubble(UsageTeamStatus):
    """
    Team status generated by Mona.
    """
    name: Literal['Illusory Bubble'] = 'Illusory Bubble'
    desc: str = (
        'When dealing Skill DMG: Remove this status and double the DMG dealt '
        'for this instance.'
    )
    version: Literal['3.3'] = '3.3'
    usage: int = 1
    max_usage: int = 1

    def value_modifier_DAMAGE_MULTIPLY(
        self, value: DamageMultiplyValue, mode: Literal['TEST', 'REAL']
    ) -> DamageMultiplyValue:
        """
        Double damage when skill damage made.
        """
        if value.target_position.player_id == self.position.player_id:
            # attack self, not activate
            return value
        if value.position.player_id != self.position.player_id:
            # not self, not activate
            return value
        if value.position.area != ObjectPositionType.CHARACTOR:
            # not charactor make damage (i.e. skill), not activate
            return value
        if self.usage > 0:
            value.damage *= 2
            if mode == 'REAL':
                self.usage -= 1
        return value


HydroCharactorTeamStatus = IllusoryBubble | IllusoryBubble
