name: pytest

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: |
        pip install -e ".[dev]"

    - name: Run tests with coverage
      run: |
        python -m setuptools_scm
        python -m pytest --cov
        coverage xml

    - name: Upload coverage to Coveralls
      if: github.ref == 'refs/heads/master'
      uses: coverallsapp/github-action@v2
